name: frontend_tests

on:
  push:
    branches:
      - main
      - frontend

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      COOL_HOME: '.'
      PATH: '/bin/.orig/.Linux:${{ github.env.PATH }}:/bin:${{ github.env.PATH }}'
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build frontend
        run: |
          cd assignments/pa1/
          buildme frontend

      - name: Test lexer and parser
        run: |
          testme lexer parser
